const nls = {
  okay: "Okay",
  cancel: "Cancel",
  save: 'Save',
  delete: "Delete",
  areYouSure: "Are you sure?",
  addField: "New To-Do Field",
  AddField: "New To-Do",
  fieldName: "Field Name",
  fieldType: "Field Type",
  FieldNameInvlaid: "Only Alphabets are allowed. Trailing spaces are not allowed",
  addNewField: "Add Field",
  resolveError: "Please enable Files & Media permission from device settings.",
  createBackupError: "Failed to create backup",
  createBackupSuccess: "Backup created successfully.",
  saveBackupError: "Failed to save backup",
  backupFileName: "flextrack.bak",
  backupMyData: "Backup my Data",
  importMyData: "Restore from Backup",
  import: "Import",
  backupFile: "Select Backup File",
  backupFileIsRequired: "Please upload the backup file.",
  readBackupFileError: "Cannot read backup file.",
  restoreFromBackupSuccessful: "Restored from backup successfully",
  parseBackupFileError: "Backup file is invalid.",
  navbar: {
    logging: "Noting",
    brand: "FlexTrack",
    home: "Dashboard",
    reports: "Reports",
    tasks: "Tasks",
    schedule: "Schedules",
    account: "Account",
  },
  exitApp: "Exit FlexTrack",
  exitAppMessage: "You want to exit."
}
export default nls;