import generic from './generic';

const nls = {
  ...generic,
  logout: "Logout",
  logoutText: "You want to logout.",
  ViewProfile: "My Profile",
  EditProfile: "Edit Profile",
  ChangePassword: "Change Password",
  Logout: "Logout",
  HelpSupport: "Help & Support",
  About: "About Fitness Tracker",
  MyPlan: "My usage plan",
  fname: "First Name",
  lname: "Last Name",
  email: "Email",
  phone: "Phone",
  verified: "Email Verfied",
  lastLogin: "Last Login",
  memberSince: "Member Since",
  done: "Done",
  unverified: "You may be unable to recover your account.",
  ChangePasswordRequired: "Please enter your current password.",
  ChangePasswordRequiredNew: "Please enter new password.",
  invalidPassword: "Please enter valid password!",
  incorrectPassword: "Enter correct password.",
  lnameRequired: "Last Name is required",
  fnameRequired: "First Name is required",
  emailRequired: "Email is required",
  phoneRequired: "Mobile Number is required",
  invlaidPhone: "Invalid phone",
  aboutApp: "About Fitness Tracker",
  aboutText1: "Welcome to the Fitness Tracker app, your comprehensive tool to help you stay on top of your fitness goals. Whether you’re looking to create customized activities, plan your fitness schedule, or log and track your progress, this app is designed to meet all your needs.",
  aboutText2: "This app is proudly developed and owned by",
  owner: "Websitera House Private Limited.",
  aboutText3: "Our team is dedicated to providing you with the best features and user experience to help you stay on top of your fitness game.",
  appOwnership: "Ownership",
  contactMessage: "For any inquiries or support, feel free to contact us.",
  supportText1: "We’re here to help you make the most of your Fitness Tracker experience. Whether you have questions, need assistance, or want to provide feedback, we’ve got you covered.",
  supportEmail: "Mail us at:",
  supportEmailValue: "support@websiterahouse.com",
  resetAccount: "Reset Account",
  resetText: "Your all data including widgets, schedules, reports, and logs will be cleared.",
  backupData: "Backup & Restore Data",
  SwitchTheme: "Switch Theme"
}
export default nls;