import generic from './generic';

const nls = {
  ...generic,
  logout: "Logout FlexTrack",
  logoutText: "You want to logout.",
  ViewProfile: "My Profile",
  EditProfile: "Edit Profile",
  ChangePassword: "Change Password",
  Logout: "Logout",
  HelpSupport: "Help & Support",
  About: "About FlexTrack",
  MyPlan: "My usage plan",
  fname: "First Name",
  lname: "Last Name",
  email: "Email",
  phone: "Phone",
  verified: "Email Verfied",
  lastLogin: "Last Login",
  memberSince: "Member Since",
  done: "Done",
  unverified: "You may not be able to recover your account.",
  ChangePasswordRequired: "Please enter your current password.",
  ChangePasswordRequiredNew: "Please enter new password.",
  invalidPassword: "Please enter valid password!",
  incorrectPassword: "Enter correct password.",
  lnameRequired: "Last Name is required",
  fnameRequired: "First Name is required",
  emailRequired: "Email is required",
  phoneRequired: "Mobile Number is required",
  invlaidPhone: "Invalid phone",
  aboutApp: "About FlexTrack",
  aboutText1: "Welcome to the FlexTrack app, your ultimate companion for tracking not just your fitness but your entire day-to-day routine. Whether you’re working on personal goals, managing daily tasks, or building a healthier lifestyle, our app empowers you to stay organized and motivated every step of the way.",
  aboutText2: "This app is proudly developed and owned by",
  owner: "Aalok Kumar.",
  aboutText3: "Our team is dedicated to providing you with the best features and user experience to help you stay on top of your day-to-day routine.",
  appOwnership: "Ownership",
  contactMessage: "For any inquiries or support, feel free to contact us.",
  supportText1: "We’re here to help you make the most of your FlexTrack experience. Whether you have questions, need assistance, or want to provide feedback, we’ve got you covered.",
  supportEmail: "Mail us at:",
  supportEmailValue: "aalokmamtasah@gmail.com",
  resetAccount: "Reset Account",
  resetText: "Your all data including activities, schedules, tasks, and logs will be cleared.",
  backupData: "Backup & Restore Data",
  SwitchTheme: "Switch Theme",
  BiometricSettings: "Biometric Settings"
}
export default nls;