const nls = {
  authFailed: 'Authentication Failed.',
  passwordPlaceHolder: 'Enter your password',
  emailPlaceHolder: 'Enter your email',
  email: 'Email',
  password: 'Password',
  emailRequired: 'Please enter your email!',
  passwordRequired: 'Please enter your password!',
  invalidEmail: 'Please enter valid email!',
  invalidPassword: 'Please enter valid password!',
  fname: 'First Name',
  lname: 'Last Name',
  gender: 'Gender',
  phone: 'Phone',
  lnameRequired: 'Please enter last name!',
  genderRequired: 'Please select gender!',
  fnameRequired: 'Please enter first name!',
  createAccount: 'Don\'t have an account? Signup Here!',
  loginExisting: 'Already have an account? Login Here!',
  Signup:"Sign Up",
  Login:"Login",
  welcome:"Welcome to Fitness Tracker",
  SignupSubheading:"Create a new account",
  LoginSubheading:"Login to your existing account",
  logoutSuccess:"Logged out successfully!",
  loginSuccess:"Logged in successfully!"
};
export default nls;
