const nls = {
  authFailed: 'Authentication Failed.',
  passwordPlaceHolder: 'Enter your password',
  emailPlaceHolder: 'Enter your email',
  email: 'Email',
  password: 'Password',
  emailRequired: 'Please enter your email!',
  passwordRequired: 'Please enter your password!',
  invalidEmail: 'Please enter valid email!',
  invalidPassword: 'Please enter valid password!',
  fname: 'First Name',
  lname: 'Last Name',
  gender: 'Gender',
  phone: 'Mobile Number',
  lnameRequired: 'Please enter last name!',
  genderRequired: 'Please select gender!',
  fnameRequired: 'Please enter first name!',
  createAccount: 'Don\'t have an account? Signup Here!',
  loginExisting: 'Already have an account? Login Here!',
  Signup: "Sign Up",
  Login: "Login",
  welcome: "Welcome to Fitness Tracker",
  SignupSubheading: "Create a new account",
  LoginSubheading: "Login to your existing account",
  logoutSuccess: "Logged out successfully!",
  loginSuccess: "Logged in successfully!",
  confirmpassword: "Confirm Password",
  passwordMatchError: "Passwords do not match.",
  phoneRequired: "Mobile Number is required.",
  invalidMobileFormat: "Mobile number format should be 123-456-7890 or 1234567890",
  SignupError: "User registered. Please login to continue.",
  UserSessionExpired: "Session Expired. Please login again."
};
export default nls;
