const nls = {
  okay: "Okay",
  cancel: "Cancel",
  save: 'Save',
  delete: "Delete",
  areYouSure: "Are you sure?",
  addField: "Add new Form Field",
  AddField: "Add task field",
  fieldName: "Field Name",
  fieldType: "Field Type",
  FieldNameInvlaid: "Alpbhabets with spaces are allowed and no trailing space is allowed",
  addNewField: "Add Field",
  resolveError: "Failed to resolve filesystem",
  createBackupError: "Failed to create backup",
  createBackupSuccess: "Backup created successfully",
  saveBackupError: "Failed to save backup",
  backupFileName: "fitness-tracker.bak",
  backupMyData: "Backup my data",
  importMyData: "Restore from backup",
  import: "Import",
  backupFile: "Select Backup File",
  backupFileIsRequired: "Please upload the backup file.",
  readBackupFileError: "Cannot read backup file.",
  restoreFromBackupSuccessful: "Restore from backup successfully",
  parseBackupFileError: "Backup file is invalid.",
  navbar: {
    logging: "Logging",
    brand: "Fitness Tracker",
    home:"Home",
    reports:"Reports",
    tasks:"Tasks",
    schedule:"Schedules",
    account:"Account",
  }
}
export default nls;